[FIXIT] No such file or directory when downloading the definitions.
If the `base_datadir` does not exist, the `load_definitions` function will raise the following exception:

```
~/folkenv/lib/python3.8/site-packages/folktables/load_acs.py in load_definitions(root_dir, year, horizon, download)
    169 
    170     response = requests.get(url)
--> 171     with open(file_path, 'wb') as handle:
    172         handle.write(response.content)
    173 

FileNotFoundError: [Errno 2] No such file or directory: 'data/2018/1-Year/definition.csv'
```

This commit will create the `base_datadir` directory before downloading the CSV files.